database:
  driverClass: org.postgresql.Driver
  user: System.getenv("HEROKU_DATABASE_USER")
  password: System.getenv("HEROKU_DATABASE_PASSWORD")
  url: jdbc:postgresql://ec2-54-227-238-21.compute-1.amazonaws.com:5432/dfu9tl1c955kv6
  validationQuery: "/* My Example Service Service Health Check */ SELECT 1"

  # any properties specific to your JDBC driver:
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute 
